name: Run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  # Common versions
  GO_VERSION: '1.22.4'
  GOLANGCI_LINT_VERSION: 'v1.59.1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false  # The golangci-lint action does its own caching.

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_VERSION }}

      - name: Run quality control checks
        run: make vet

      - name: Run tests
        run: make test

      - name: Build
        run: make build
